version: '2'
services:
  rosmaster:
    image: "ros:kinetic-ros-core"
    container_name: rosmaster
    command:
        - roscore

  vlp:
    image: "virgiletn/ros-kinetic-vlp16"
    container_name: vlp
    environment:
        - "ROS_HOSTNAME=coucou"
        - "ROS_MASTER_URI=http://coucou:11311"
